config/routes.rb
Rails.application.routes.draw do
  resources :series do
    member do
      get :top5
      get :statistics
    end
  end
  resources :pictures
  resources :relations

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pictures#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include IdentityCache

  belongs_to :series, touch: true
  belongs_to :sortable, polymorphic: true

  has_many :larger_than_relations, foreign_key: :item1_id,
                                   class_name: 'Relation',
                                   dependent: :destroy,
                                   inverse_of: 'item1'
  has_many :smaller_items, through: :larger_than_relations, class_name: 'Item', source: :item2
  has_many :smaller_than_relations, foreign_key: :item2_id,
                                    class_name: 'Relation',
                                    dependent: :destroy,
                                    inverse_of: 'item2'
  has_many :larger_items, through: :smaller_than_relations, class_name: 'Item', source: :item1

  before_validation :set_counts, on: :create

  scope :without_relations, -> { where.missing(:larger_than_relations, :smaller_than_relations) }

  def make_bigger_than(other)
    Items::MakeBiggerJob.perform_later(item1_id: id, item2_id: other.id)
  end

  def <=>(other)
    return 1 if larger_than?(other)
    return -1 if smaller_than?(other)

    relations_weight <=> other.relations_weight
  end

  def larger_than?(other)
    ItemCache.larger_than?(id, other.id)
  end

  def smaller_than?(other)
    ItemCache.smaller_than?(id, other.id)
  end

  def update_relations_count!
    update(relations_count: larger_than_relations.count + smaller_than_relations.count,
           relations_weight: larger_than_relations.count - smaller_than_relations.count)
  end

  def to_s
    "id: #{id}, value: #{value}"
  end

  private

  def set_counts
    self.relations_count = 0
    self.relations_weight = 0
  end
end

app/models/item_cache.rb
# frozen_string_literal: true

class ItemCache
  include Singleton

  @item_cache = {}

  def self.larger_than?(item1_id, item2_id)
    @item_cache ||= {}
    @item_cache[item1_id] ||= Relation.select(:item1_id, :item2_id).where(item1_id:)

    @item_cache[item1_id].include?(item2_id)
  end

  def self.reset!
    @item_cache = {}
  end

  def self.smaller_than?(item1_id, item2_id)
    larger_than?(item2_id, item1_id)
  end
end

app/models/item_touple.rb
class ItemTouple
  include ActiveModel::Validations

  attr_accessor :item1, :item2

  validate :items_are_not_equal
  validate :items_have_no_relation

  def initialize(item1, item2)
    @item1 = item1
    @item2 = item2
  end

  private

  def items_are_not_equal
    errors.add(:item1, 'Items are equal.') if item1 == item2
  end

  def items_have_no_relation
    errors.add(:item1, 'Elements have a relation already.') if Relation.any_for?(item1.id, item2.id)
  end
end

app/models/picture.rb
# frozen_string_literal: true

class Picture < ApplicationRecord
  include IdentityCache
  has_one :item, as: :sortable, dependent: :destroy

  validates :path, presence: true
end

app/models/relation.rb
# frozen_string_literal: true

class Relation < ApplicationRecord
  include IdentityCache

  belongs_to :item1, class_name: 'Item', touch: true
  belongs_to :item2, class_name: 'Item', touch: true

  validates :item1_id, uniqueness: { scope: :item2_id }
  validate :items_are_different

  cache_index :item1_id, :item2_id, unique: true

  after_create { ItemCache.reset! }
  after_create :update_items_relations_count
  after_destroy :update_items_relations_count

  def self.any_for?(item1_id, item2_id)
    fetch_by_item1_id_and_item2_id(item1_id, item2_id).present? ||
      fetch_by_item1_id_and_item2_id(item2_id, item1_id).present?
  end

  private

  def items_are_different
    errors.add(:item1, "can't be identical to item2") if item2 == item1
  end

  def update_items_relations_count
    item1.update_relations_count!
    item2.update_relations_count!
  end
end

app/models/series.rb
# frozen_string_literal: true

class Series < ApplicationRecord
  include IdentityCache

  has_many :items, dependent: :destroy

  def find_missing_touple(item1: nil)
    scope = items
    result = Items::FindMissingTouple.call!(item1: item1, scope:)
    [result.touple.first, result.touple.last].shuffle
  end

  def top5
    items.shuffle.sort.reverse.first(5)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true

class PicturesController < ApplicationController
  def show
    @picture = Picture.fetch(params[:id])
    fresh_when(@picture)

    send_file(@picture.path, disposition: 'inline')
  end
end

app/controllers/relations_controller.rb
# frozen_string_literal: true

class RelationsController < ApplicationController
  def create
    Items::MakeBiggerJob.perform_later(item1_id: create_params[:item1_id],
                                       item2_id: create_params[:item2_id])

    item1 = Item.fetch(create_params[:item1_id])
    sticky = ActiveRecord::Type::Boolean.new.deserialize(create_params[:sticky])
    if sticky
      redirect_to series_path(item1.series, picture_id: item1.sortable_id, sticky:)
    else
      redirect_to series_path(item1.series)
    end
  end

  private

  def create_params
    params[:relation]
  end
end

app/controllers/series_controller.rb
# frozen_string_literal: true

class SeriesController < ApplicationController
  def show
    @series = Series.fetch(params[:id])
    fresh_when(@series)

    @sticky = sticky
    result = Items::FindMissingTouple.call(item1:, scope: @series.items)
    @touple = result.touple if result.success?
  end

  def top5
    @series = Series.fetch(params[:id])
    fresh_when(@series)

    @top5 = @series.top5
  end

  def statistics
    @series = Series.fetch(params[:id])
    fresh_when(@series)

    @items_count = @series.items.count
    @without_relations_count = @series.items.without_relations.count
    @highest_relation_count = @series.items.maximum(:relations_count)
    @lowest_relation_count = @series.items.minimum(:relations_count)
  end

  private

  def sticky
    ActiveRecord::Type::Boolean.new.deserialize(params[:sticky])
  end

  def item1
    picture_id = params[:picture_id]
    return Picture.find(picture_id).item if picture_id

    nil
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true

module PicturesHelper
end

app/helpers/relations_helper.rb
# frozen_string_literal: true

module RelationsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title T::Sort
    %meta{ name: :viewport, content: 'width=device-width,initial-scale=1' }
    %meta{ name: 'turbo-refresh-method', content: :morph }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'tailwind', 'data-turbo-track': 'reload'
    = yield :head
    = javascript_importmap_tags

  %body.h-full.font-mono.antialiased.bg-teal-900.text-teal-300
    %main.container.mx-auto.mt-28.px-5.flex
      = yield

app/views/pictures/_picture.html.haml
- cache(picture) do

  %img.inline-block.align-top.rounded-md.bg-gray-200.object-cover.lg-aspect-auto{ src: picture_path(picture), width: '300px' }

app/views/pictures/index.html.haml
= form_for(Relation.new) do |f|
  = f.hidden_field :item1_id, value: @touple.first.id
  = f.hidden_field :item2_id, value: @touple.last.id
  = f.button do
    = render partial: 'picture', locals: { picture: @touple.first.sortable }

= form_for(Relation.new) do |f|
  = f.hidden_field :item2_id, value: @touple.first.id
  = f.hidden_field :item1_id, value: @touple.last.id
  = f.button do
    = render partial: 'picture', locals: { picture: @touple.last.sortable }

app/views/series/show.html.haml
.bg-white
  .mx-auto.py-8.max-w-7xl.px-8
    = turbo_frame_tag "form_#{dom_id(@series)}" do
      - if @touple.present?
        %h2.text-2xl.font-bold.tracking-tight.text-gray-900 Which one do you prefer?
        .grid.grid-cols-2.gap-x-6.gap-y-10.xl:gap-x-8
          %div
            = form_for(Relation.new) do |f|
              = f.hidden_field :sticky, value: @sticky
              = f.hidden_field :item1_id, value: @touple.item1.id
              = f.hidden_field :item2_id, value: @touple.item2.id
              = f.button do
                = render partial: 'pictures/picture', locals: { picture: @touple.item1.sortable }

          %div
            = form_for(Relation.new, class: ['max-w-xl']) do |f|
              = f.hidden_field :sticky, value: @sticky
              = f.hidden_field :item2_id, value: @touple.item1.id
              = f.hidden_field :item1_id, value: @touple.item2.id
              = f.button do
                = render partial: 'pictures/picture', locals: { picture: @touple.item2.sortable }
      - else
        %h2.text-2xl.font-bold.tracking-tight.text-gray-900 No more items to compare

  .mx-auto.py-8.max-w-7xl.px-8
    = turbo_frame_tag "statistics_#{dom_id(@series)}", src: statistics_series_path(@series), loading: 'lazy'
  .mx-auto.py-8.max-w-7xl.px-8
    = turbo_frame_tag "top5_#{dom_id(@series)}", src: top5_series_path(@series), loading: 'lazy'

app/views/series/statistics.html.haml
= turbo_frame_tag "statistics_#{dom_id(@series)}" do
  %h2.text-2xl.font-bold.tracking-tight.text-gray-900 Statistics
  %p= "#{@items_count} #{'item'.pluralize(@items_count)} total"
  %p= "#{@without_relations_count} #{'item'.pluralize(@without_relations_count)} without relations"
  %p= "relation_count spread: #{@lowest_relation_count} to #{@highest_relation_count}"

app/views/series/top5.html.haml
= turbo_frame_tag "top5_#{dom_id(@series)}" do
  %h2.text-2xl.font-bold.tracking-tight.text-gray-900 Top 5 Items
  .grid.grid-cols-4.gap-x-6.gap-y-10.xl:gap-x-8.inline-block.align-top
    - @top5.each do |item|
      %img.inline-block.align-top.aspect-square.rounded-md.bg-gray-200.object-cover.lg-aspect-auto.lg:h-80{ src: picture_path(item.sortable), width: '150px' }